-- updated faster sql:
CREATE MATERIALIZED VIEW mv_predicted_reports AS
SELECT
  pr.id AS report_id,                         -- stable unique key (row_number() over (order by dr.dtxsid, p.name,s.name) as id is very slow)
  dr.dtxsid,
  dr.dtxcid,
  m.id AS model_id,
  m.name_ccd AS model_name,
  p.name_ccd AS prop_name,
  pc.name AS prop_category,
  s.name AS source_name,
  convert_from(pr.file_json, 'UTF8') AS report_json,
  convert_from(pr.file_html, 'UTF8') AS report_html,
  current_date AS export_date,
  '3.0.0' AS data_version
FROM qsar_models.prediction_reports pr
JOIN qsar_models.predictions_dashboard pd
  ON pd.id = pr.fk_predictions_dashboard_id
JOIN qsar_models.models m
  ON m.id = pd.fk_model_id
JOIN qsar_models.sources s
  ON s.id = m.fk_source_id
JOIN qsar_datasets.datasets d
  ON d."name" = m.dataset_name
JOIN qsar_datasets.properties p
  ON p.id = d.fk_property_id
JOIN qsar_models.dsstox_records dr
  ON pd.dtxcid = dr.dtxcid
 AND dr.fk_dsstox_snapshot_id = 4                 -- keep selectivity high
LEFT JOIN qsar_datasets.properties_in_categories pic
  ON p.id = pic.fk_property_id
LEFT JOIN qsar_datasets.property_categories pc
  ON pc.id = pic.fk_property_category_id;


-- Unique index for REFRESH CONCURRENTLY
CREATE UNIQUE INDEX mv_predicted_reports_report_id_uq
  ON mv_predicted_reports (report_id);

-- Speed common sorts and filters
CREATE INDEX mv_predicted_reports_order_idx
  ON mv_predicted_reports (dtxsid, prop_name, source_name);

CREATE INDEX mv_predicted_reports_model_id_idx
  ON mv_predicted_reports (model_id);

CREATE INDEX mv_predicted_reports_source_name_idx
  ON mv_predicted_reports (source_name);

-- If you often filter by prop_category:
CREATE INDEX mv_predicted_reports_prop_category_idx
  ON mv_predicted_reports (prop_category);

-- Refresh strategy (PostgreSQL)
REFRESH MATERIALIZED VIEW CONCURRENTLY mv_predicted_reports;

--physical ordering via CLUSTER (run after each refresh)
REFRESH MATERIALIZED VIEW CONCURRENTLY mv_predicted_reports;
CLUSTER mv_predicted_reports USING mv_predicted_reports_order_idx;
ANALYZE mv_predicted_reports;


-- is following needed after doing the cluster sort?
SELECT *
FROM mv_predicted_reports
ORDER BY dtxsid, prop_name, source_name;


-- Export reports
CREATE MATERIALIZED VIEW mv_predicted_reports as
select
--       row_number() over (order by dr.dtxsid, p.name,s.name) as id,
--        row_number()  over () as id,
       dr.dtxsid,
       dr.dtxcid,
       m.id as model_id,
       m.name_ccd as model_name,
       p.name_ccd as prop_name,
       pc.name as prop_category,
       s.name as source_name,
       convert_from(pr.file_json,'UTF-8') as report_json,
       convert_from(pr.file_html,'UTF-8') as report_html,
       current_date as export_date,
       '3.1.0' as data_version
from qsar_models.prediction_reports pr
join qsar_models.predictions_dashboard pd on pd.id = pr.fk_predictions_dashboard_id
join qsar_models.models m on m.id=pd.fk_model_id
join qsar_models.sources s on m.fk_source_id = s.id
join qsar_datasets.datasets d on d."name" =m.dataset_name
join qsar_datasets.properties p on p.id=d.fk_property_id
-- join qsar_models.dsstox_records dr on pd.fk_dsstox_records_id=dr.id
join qsar_models.dsstox_records dr on pd.dtxcid = dr.dtxcid --join based on dtxcid instead of fk so that have up to date dtxsids
left join qsar_datasets.properties_in_categories pic on p.id = pic.fk_property_id
left join qsar_datasets.property_categories pc on pic.fk_property_category_id = pc.id
where dr.fk_dsstox_snapshot_id=4
-- and pd.dtxcid like 'DTXCID00%'
-- and s.name='OPERA2.8'
-- and s.name='TEST5.1.3'
-- and dr.dtxsid='DTXSID7020182'; -- BPA
-- and dr.dtxsid='DTXSID3039242' -- benzene
;



select count(distinct  dtxcid) from public.mv_predicted_reports;


SHOW statement_timeout;


refresh materialized view mv_predicted_reports;

GRANT SELECT ON mv_predicted_reports TO app_pentaho;

create index mv_predicted_reports_dtxsid_index  on public.mv_predicted_reports (dtxsid);
create index mv_predicted_reports_source_name_index  on public.mv_predicted_reports (source_name);

create index mv_predicted_reports_id  on mv_predicted_reports (id);

comment on materialized view mv_predicted_reports is 'QSAR model prediction json and html reports materialized view';

comment on column mv_predicted_reports.id is 'Autogenerated id for sorting';
comment on column mv_predicted_reports.dtxsid is 'DSSTox Substance id';
comment on column mv_predicted_reports.dtxcid is 'DSSTox Compound id';
comment on column mv_predicted_reports.model_id is 'ID of the model in qsar_models.models table (e.g. 123)';
comment on column mv_predicted_reports.model_name is 'Name of the model (e.g. ACD_Prop_Polarizability)';
comment on column mv_predicted_reports.prop_name is 'Property name (e.g. Boiling Point)';
comment on column mv_predicted_reports.prop_category is 'Property category (e.g. Physchem)';
comment on column mv_predicted_reports.source_name is 'Name of the model source (e.g. Percepta2023.1.2)';
comment on column mv_predicted_reports.report_json is 'JSON prediction report file';
comment on column mv_predicted_reports.report_html is 'HTML prediction report file';
comment on column mv_predicted_reports.export_date is 'When the materialized view was updated';
comment on column mv_predicted_reports.data_version is 'Version of the materialized view (see public.materialized_view_version_history for description of changes made)';


VACUUM (ANALYZE, VERBOSE, FULL) qsar_models.prediction_reports;

SELECT * FROM pg_stat_activity;

SELECT
    pid,
    now() - pg_stat_activity.query_start AS duration,
    query,
    state,
    backend_type
FROM
    pg_stat_activity
WHERE
    backend_type = 'client backend'
ORDER BY
    backend_start DESC;



pg_terminate_backend(15557);


select * from public.materialized_view_version_history mvvh 
order by materialized_view,version;



SELECT
  pr.id AS report_id,                         -- stable unique key (row_number() over (order by dr.dtxsid, p.name,s.name) as id is very slow)
  dr.dtxsid,
  dr.dtxcid,
  m.id AS model_id,
  m.name_ccd AS model_name,
  p.name_ccd AS prop_name,
  pc.name AS prop_category,
  s.name AS source_name,
  convert_from(pr.file_json, 'UTF8') AS report_json,
  convert_from(pr.file_html, 'UTF8') AS report_html,
  current_date AS export_date,
  '3.0.0' AS data_version
FROM qsar_models.prediction_reports pr
JOIN qsar_models.predictions_dashboard pd
  ON pd.id = pr.fk_predictions_dashboard_id
JOIN qsar_models.models m
  ON m.id = pd.fk_model_id
JOIN qsar_models.sources s
  ON s.id = m.fk_source_id
JOIN qsar_datasets.datasets d
  ON d."name" = m.dataset_name
JOIN qsar_datasets.properties p
  ON p.id = d.fk_property_id
JOIN qsar_models.dsstox_records dr
  ON pd.dtxcid = dr.dtxcid
 AND dr.fk_dsstox_snapshot_id = 4                 -- keep selectivity high
LEFT JOIN qsar_datasets.properties_in_categories pic
  ON p.id = pic.fk_property_id
LEFT JOIN qsar_datasets.property_categories pc
  ON pc.id = pic.fk_property_category_id
  where s.name = 'OPERA2.8' and dr.dtxsid='DTXSID3039242';
