CREATE MATERIALIZED VIEW mv_model_files as
select
    row_number() over (order by s.name, p.name, ft.name) as id,
    m.id as model_id,
    m.name_ccd as model_name,
    s.name as model_source,
    ft.id as file_type_id,
    ft.name as file_type_name,
    p.name_ccd as property_name,
    mf.file as file_bytes,
    current_date as export_date,
    '1.1.1' as data_version
from qsar_models.model_files mf
join qsar_models.models m on mf.fk_model_id = m.id
join qsar_models.file_types ft on mf.fk_file_type_id = ft.id
join qsar_models.sources s on m.fk_source_id = s.id
join qsar_datasets.datasets ds on ds."name" =m.dataset_name
join qsar_datasets.properties p on p.id=ds.fk_property_id
-- order by model_source, m.name, ft.name
;

refresh materialized view mv_model_files;

create index v_model_files_index_model_id    on mv_model_files (model_id,file_type_id);
GRANT SELECT ON mv_model_files TO arashid;
GRANT SELECT ON mv_model_files TO app_pentaho;
comment on materialized view mv_model_files is 'Model files for prediction reports';
comment on column mv_model_files.id is 'Autogenerated id';
comment on column mv_model_files.model_id is 'Foreign key for model: qsar_models.models.id';
comment on column mv_model_files.model_name is 'Name of the model: qsar_models.models.name_ccd';
comment on column mv_model_files.model_source is 'Source of the model: qsar_models.sources.name';
comment on column mv_model_files.file_type_id is 'Foreign key for file type: qsar_models.file_types.id';
comment on column mv_model_files.file_type_name is 'File type name: qsar_models.file_types.name';
comment on column mv_model_files.property_name is 'Property name: qsar_datasets.properties.name_ccd';
comment on column mv_model_files.file_bytes is 'Model file data: qsar_models.model_files.file';
comment on column mv_model_files.export_date is 'Date the record was exported';
comment on column mv_model_files.data_version is 'Version of the materialized view';




select mf.fk_model_id,mf.fk_file_type_id  from qsar_models.model_files mf
where mf.fk_model_id=1161;

-- look at view without file:
select mf.model_id,mf.file_type_id, mf.model_name,mf.property_name,mf.file_type_name,export_date, data_version  from mv_model_files mf;


update qsar_models.models set name_ccd=trim(name_ccd) where name_ccd like '%TEST%'


select * from materialized_view_version_history
order by materialized_view,version;


select mf.file_bytes from mv_model_files mf
                     where model_name='OPERA_AOH' and file_type_name='Histogram plot';



select mf.model_id, mf.file_type_name,  mf.model_name from public.mv_model_files mf;



select count(distinct (dtxsid)) from mv_experimental_data mv
where prop_name='Henry''s Law Constant';